/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversionToolsRouteImport } from './routes/conversion-tools'
import { Route as ConnectionToolDevicesRouteImport } from './routes/connection-tool-devices'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NetworksIndexRouteImport } from './routes/networks.index'
import { Route as NetworksNetworkIdRouteImport } from './routes/networks.$networkId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionToolsRoute = ConversionToolsRouteImport.update({
  id: '/conversion-tools',
  path: '/conversion-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionToolDevicesRoute = ConnectionToolDevicesRouteImport.update({
  id: '/connection-tool-devices',
  path: '/connection-tool-devices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksIndexRoute = NetworksIndexRouteImport.update({
  id: '/networks/',
  path: '/networks/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksNetworkIdRoute = NetworksNetworkIdRouteImport.update({
  id: '/networks/$networkId',
  path: '/networks/$networkId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connection-tool-devices': typeof ConnectionToolDevicesRoute
  '/conversion-tools': typeof ConversionToolsRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
  '/runs': typeof RunsRoute
  '/scenarios': typeof ScenariosRoute
  '/users': typeof UsersRoute
  '/networks/$networkId': typeof NetworksNetworkIdRoute
  '/networks/': typeof NetworksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connection-tool-devices': typeof ConnectionToolDevicesRoute
  '/conversion-tools': typeof ConversionToolsRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
  '/runs': typeof RunsRoute
  '/scenarios': typeof ScenariosRoute
  '/users': typeof UsersRoute
  '/networks/$networkId': typeof NetworksNetworkIdRoute
  '/networks': typeof NetworksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connection-tool-devices': typeof ConnectionToolDevicesRoute
  '/conversion-tools': typeof ConversionToolsRoute
  '/dashboard': typeof DashboardRoute
  '/results': typeof ResultsRoute
  '/runs': typeof RunsRoute
  '/scenarios': typeof ScenariosRoute
  '/users': typeof UsersRoute
  '/networks/$networkId': typeof NetworksNetworkIdRoute
  '/networks/': typeof NetworksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connection-tool-devices'
    | '/conversion-tools'
    | '/dashboard'
    | '/results'
    | '/runs'
    | '/scenarios'
    | '/users'
    | '/networks/$networkId'
    | '/networks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connection-tool-devices'
    | '/conversion-tools'
    | '/dashboard'
    | '/results'
    | '/runs'
    | '/scenarios'
    | '/users'
    | '/networks/$networkId'
    | '/networks'
  id:
    | '__root__'
    | '/'
    | '/connection-tool-devices'
    | '/conversion-tools'
    | '/dashboard'
    | '/results'
    | '/runs'
    | '/scenarios'
    | '/users'
    | '/networks/$networkId'
    | '/networks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionToolDevicesRoute: typeof ConnectionToolDevicesRoute
  ConversionToolsRoute: typeof ConversionToolsRoute
  DashboardRoute: typeof DashboardRoute
  ResultsRoute: typeof ResultsRoute
  RunsRoute: typeof RunsRoute
  ScenariosRoute: typeof ScenariosRoute
  UsersRoute: typeof UsersRoute
  NetworksNetworkIdRoute: typeof NetworksNetworkIdRoute
  NetworksIndexRoute: typeof NetworksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversion-tools': {
      id: '/conversion-tools'
      path: '/conversion-tools'
      fullPath: '/conversion-tools'
      preLoaderRoute: typeof ConversionToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection-tool-devices': {
      id: '/connection-tool-devices'
      path: '/connection-tool-devices'
      fullPath: '/connection-tool-devices'
      preLoaderRoute: typeof ConnectionToolDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks/': {
      id: '/networks/'
      path: '/networks'
      fullPath: '/networks/'
      preLoaderRoute: typeof NetworksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks/$networkId': {
      id: '/networks/$networkId'
      path: '/networks/$networkId'
      fullPath: '/networks/$networkId'
      preLoaderRoute: typeof NetworksNetworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionToolDevicesRoute: ConnectionToolDevicesRoute,
  ConversionToolsRoute: ConversionToolsRoute,
  DashboardRoute: DashboardRoute,
  ResultsRoute: ResultsRoute,
  RunsRoute: RunsRoute,
  ScenariosRoute: ScenariosRoute,
  UsersRoute: UsersRoute,
  NetworksNetworkIdRoute: NetworksNetworkIdRoute,
  NetworksIndexRoute: NetworksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
